INSERT INTO USER (FIRST_NAME, LAST_NAME) VALUES ('Karlos', 'Chita');
INSERT INTO USER (FIRST_NAME, LAST_NAME) VALUES ('Claudia', 'Chita');
INSERT INTO USER (FIRST_NAME, LAST_NAME) VALUES ('Susana', 'Chita');
INSERT INTO USER (FIRST_NAME, LAST_NAME) VALUES ('Carlos', 'Chita');
INSERT INTO USER (FIRST_NAME, LAST_NAME) VALUES ('Leonor', 'Pocasangre');
COMMIT;
